[build-system]
requires = ["setuptools>=41.0.1", "wheel", "scikit-build>=0.9.0", "numpy", "cmake", "cython", "ninja", "cffi"]

#[tool.cibuildwheel]
#manylinux-x86_64-image = "quay.io/erotemic/manylinux-for:x86_64-fletch1.5.0-opencv"
